app:
    resource: "@AppBundle/Controller/"
    type:     annotation

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

acme_security:
    resource: "@AcmeSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

acme_task:
    resource: "@AcmeTaskBundle/Controller/"
    type:     annotation

task_new:
    path: /formulario
    defaults: {_controller: AcmeTaskBundle:Default:new}

login:
    pattern:   /login
    defaults:  { _controller: AcmeSecurityBundle:Security:login }
login_check:
    pattern:   /login_check

users_show:
    path: /users/{user_id}
    defaults: {controller: UsersBundle:Default:user }
    methods: [GET]
    requirements:
      _format: html
      _locale: es|en

users_list:
    path: /users
    defaults: {controller: UsersBundle:Default:userlist }
    methods: [GET]
    requirements:
        _format: html
        _locale: es|en

users_create:
    path: /users/create
    defaults: {controller: UsersBundle:Default:usercreate }
    methods: [POST]
    requirements:
       _format: html
       _locale: es|en
