root:
    path: /
    defaults:
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /en
        permanent: true
app:
    resource: "@AppBundle/Controller/"
    type:     annotation

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

acme_security:
    resource: "@AcmeSecurityBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}/security

acme_task:
    resource: "@AcmeTaskBundle/Controller/"
    type:     annotation

task_new:
    path: /{_locale}/formulario
    defaults: {_controller: AcmeTaskBundle:Default:new}

login:
    pattern:   /{_locale}/login
    defaults:  { _controller: AcmeSecurityBundle:Security:login, _locale: en}
    requirements:
        _locale: en|es
login_check:
    pattern:   /login_check

logout:
    path: /logout

users:
    resource: "@AcmeUserBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}


admin:
    resource: "@AppBundle/Controller/"
    type:     annotation
    prefix:   /{_locale}

