acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

acme_security:
    resource: "@AcmeSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

acme_task:
    resource: "@AcmeTaskBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

pagina2:
    path: /page2/{page}
    defaults: {_controller: AppBundle:Pagina2, page: 1}
    requirements:
        page: \d+

pagina2_show:
    path:    /pagina2/{slug}
    defaults: {_controller: AppBundle:Pagina2: show}

task_new:
    path: /formulario
    defaults: {_controller: AcmeTaskBundle:Default:new}

login:
    pattern:   /login
    defaults:  { _controller: AcmeSecurityBundle:Security:login }
login_check:
    pattern:   /login_check

users:
  path: /users/{user_id}
  defaults: {controller: UsersBundle:Default:user }
  methods: [GET]
  requirements:
      _format: html
      _locale: es|en

users:
  path: /users
  defaults: {controller: UsersBundle:Default:userlist }
  methods: [GET]
  requirements:
    _format: html
    _locale: es|en

users:
  path: /users/create
  defaults: {controller: UsersBundle:Default:usercreate }
  methods: [POST]
    requirements:
      _format: html
      _locale: es|en

