app:
    resource: "@AppBundle/Controller/"
    type:     annotation

acme_user:
    resource: "@AcmeUserBundle/Resources/config/routing.yml"
    prefix:   /

acme_security:
    resource: "@AcmeSecurityBundle/Controller/"
    type:     annotation
    prefix:   /

acme_task:
    resource: "@AcmeTaskBundle/Controller/"
    type:     annotation

task_new:
    path: /formulario
    defaults: {_controller: AcmeTaskBundle:Default:new}

login:
    path: /{_locale}/
    pattern:   /login
    defaults:  { _controller: AcmeSecurityBundle:Security:login, _locale: en}
    requirements:
        _locale: en|fr|de
login_check:
    pattern:   /login_check

logout:
    path: /logout

users:
    resource: "@AcmeUserBundle/Controller/"
    type:     annotation

admin:
    resource: "@AppBundle/Controller/"
    type:     annotation

